In [1]:
import numpy as np

In [2]:
board = np.zeros((9,9), dtype='int')

In [3]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

    [0,0,0,6,0,0,1,0,7],
    [6,8,0,9,5,1,3,0,0],
    [0,0,3,0,0,2,5,6,8],
    [0,4,0,8,1,0,0,2,0],
    [0,0,0,0,0,0,8,5,0],
    [0,9,0,0,6,5,0,7,3],
    [4,0,9,0,0,3,0,8,5],
    [1,6,2,0,0,9,0,3,0],
    [5,0,0,7,0,6,0,0,0]

In [4]:
example = [
    [0,0,0,6,0,0,1,0,7],
    [6,8,0,9,5,1,3,0,0],
    [0,0,3,0,0,2,5,6,8],
    [0,4,0,8,1,0,0,2,0],
    [0,0,0,0,0,0,8,5,0],
    [0,9,0,0,6,5,0,7,3],
    [4,0,9,0,0,3,0,8,5],
    [1,6,2,0,0,9,0,3,0],
    [5,0,0,7,0,6,0,0,0]
]

In [5]:
board = np.array(example)

In [6]:
temp = np.zeros((3,3,3,3), dtype='int')

In [7]:
for i in range(9):
    for j in range(9):
        temp[i//3,j//3,i%3,j%3] = board[i,j]

In [8]:
temp

array([[[[0, 0, 0],
         [6, 8, 0],
         [0, 0, 3]],

        [[6, 0, 0],
         [9, 5, 1],
         [0, 0, 2]],

        [[1, 0, 7],
         [3, 0, 0],
         [5, 6, 8]]],


       [[[0, 4, 0],
         [0, 0, 0],
         [0, 9, 0]],

        [[8, 1, 0],
         [0, 0, 0],
         [0, 6, 5]],

        [[0, 2, 0],
         [8, 5, 0],
         [0, 7, 3]]],


       [[[4, 0, 9],
         [1, 6, 2],
         [5, 0, 0]],

        [[0, 0, 3],
         [0, 0, 9],
         [7, 0, 6]],

        [[0, 8, 5],
         [0, 3, 0],
         [0, 0, 0]]]])

In [9]:
board

array([[0, 0, 0, 6, 0, 0, 1, 0, 7],
       [6, 8, 0, 9, 5, 1, 3, 0, 0],
       [0, 0, 3, 0, 0, 2, 5, 6, 8],
       [0, 4, 0, 8, 1, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 8, 5, 0],
       [0, 9, 0, 0, 6, 5, 0, 7, 3],
       [4, 0, 9, 0, 0, 3, 0, 8, 5],
       [1, 6, 2, 0, 0, 9, 0, 3, 0],
       [5, 0, 0, 7, 0, 6, 0, 0, 0]])

In [10]:
cell_name = {
    (0,0) : 'top left',
    (0,1) : 'top middle',
    (0,2) : 'top right',
    (1,0) : 'center left',
    (1,1) : 'center middle',
    (1,2) : 'center right',
    (2,0) : 'bottom left',
    (2,1) : 'bottom middle',
    (2,2) : 'bottom right'
}

In [11]:
def solve(board):
    n = 1
    solve_rules = []
    counter=1
    while(counter>0):
        counter=0
        for n in range(1,10):
            nums = np.where(temp == n)
            for i in range(3):
                for j in range(3):
                    num = zip(nums[0], nums[1])
                    if (i,j) not in num:
        #                 print('I am here')
                        c_rows = nums[2][nums[0] == i]
                        c_cols = nums[3][nums[1] == j]
                        zero_cell_rows, zero_cell_cols = np.where(temp[i,j] == 0)
                        zeros = zip(zero_cell_rows, zero_cell_cols)
                        p_c = 0
                        for z in zeros:
                            if z[0] not in c_rows and z[1] not in c_cols:
                                row,col = z
                                p_c += 1
                        if p_c == 1:
                            counter += 1
                            temp[i,j,row,col] = n
                            txt = 'Put %d in %d row, %d column in %s cell because of %d in '%(n,row+1,col+1,cell_name[(i,j)],n)
                            txt += ', '.join(map(lambda x: str(x+1),c_rows))
                            if len(c_rows) > 1:
                                txt += ' rows'
                            elif len(c_rows) == 1:
                                txt += ' row'
                            if len(c_cols) != 0:
                                txt += ' and in '
                                txt += ', '.join(map(lambda x: str(x+1),c_cols)) 
                                if len(c_cols) > 1:
                                    txt += ' cols'
                                elif len(c_cols) == 1:
                                    txt += ' col'

                            solve_rules.append(txt)


In [12]:
def check_all_nums(board, temp):
    solve_rules = []
    counter = 0
    for n in range(1,10):
        nums = np.where(temp == n)
        for i in range(3):
            for j in range(3):
                num = zip(nums[0], nums[1])
                if (i,j) not in num:
    #                 print('I am here')
                    c_rows = nums[2][nums[0] == i]
                    c_cols = nums[3][nums[1] == j]
                    zero_cell_rows, zero_cell_cols = np.where(temp[i,j] == 0)
                    zeros = zip(zero_cell_rows, zero_cell_cols)
                    p_c = 0
                    for z in zeros:
                        if z[0] not in c_rows and z[1] not in c_cols:
                            row,col = z
                            p_c += 1
                    if p_c == 1:
                        counter += 1
                        temp[i,j,row,col] = n
                        board[3*i+row, 3*j+col] = n
                        txt = 'Put %d in %d row, %d column in %s cell because of %d in '%(n,row+1,col+1,cell_name[(i,j)],n)
                        txt += ', '.join(map(lambda x: str(x+1),c_rows))
                        if len(c_rows) > 1:
                            txt += ' rows'
                        elif len(c_rows) == 1:
                            txt += ' row'
                        if len(c_cols) != 0:
                            txt += ' and in '
                            txt += ', '.join(map(lambda x: str(x+1),c_cols)) 
                            if len(c_cols) > 1:
                                txt += ' cols'
                            elif len(c_cols) == 1:
                                txt += ' col'

                        solve_rules.append(txt)
    return solve_rules, counter


def fill_rows(board):
    rules = []
    counter = 0
    for i in range(0,9):
        n = np.where(board[i] == 0)[0]
        if(len(n) == 1):
            v = 45 - sum(board[i])
            board[i, n[0]] = v
            text = "Put %d in %d row and %d column" % (v, i+1, n[0]+1)
            rules.append(text)
            counter += 1
    return rules, counter

def fill_cols(board):
    rules = []
    counter = 0
    for i in range(0,9):
        n = np.where(board[:,i] == 0)[0]
        if(len(n) == 1):
            v = 45 - sum(board[i])
            board[n[0], i] = v
            text = "Put %d in %d row and %d column" % (v, n[0]+1, i+1)
            rules.append(text)
            counter += 1
    return rules, counter

In [13]:
board

array([[0, 0, 0, 6, 0, 0, 1, 0, 7],
       [6, 8, 0, 9, 5, 1, 3, 0, 0],
       [0, 0, 3, 0, 0, 2, 5, 6, 8],
       [0, 4, 0, 8, 1, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 8, 5, 0],
       [0, 9, 0, 0, 6, 5, 0, 7, 3],
       [4, 0, 9, 0, 0, 3, 0, 8, 5],
       [1, 6, 2, 0, 0, 9, 0, 3, 0],
       [5, 0, 0, 7, 0, 6, 0, 0, 0]])

In [14]:
def solve(board):
    temp = np.zeros((3,3,3,3), dtype='int')
    for i in range(9):
        for j in range(9):
            temp[i//3,j//3,i%3,j%3] = board[i,j]
#     print(temp)
    n = 1
    solve_rules = []
    counter=1
    while(counter>0):
        counter = 0
        sr, cr = check_all_nums(board, temp)
        solve_rules.extend(sr)
        counter += cr
        
        sr, cr = fill_rows(board)
        solve_rules.extend(sr)
        counter += cr
        
        sr, cr = fill_cols(board)
        solve_rules.extend(sr)
        counter += cr
#         print("counter is", counter)
    co = set(np.unique(board, return_counts=True)[1])
    if 9 in co and len(co) == 1:
        return True, solve_rules, board
    else:
        return False, solve_rules, board
        

In [15]:
is_solved, rules, board = solve(board)

In [16]:
board

array([[2, 5, 4, 6, 3, 8, 1, 9, 7],
       [6, 8, 7, 9, 5, 1, 3, 4, 2],
       [9, 1, 3, 4, 7, 2, 5, 6, 8],
       [3, 4, 5, 8, 1, 7, 9, 2, 6],
       [7, 2, 6, 3, 9, 4, 8, 5, 1],
       [8, 9, 1, 2, 6, 5, 4, 7, 3],
       [4, 7, 9, 1, 2, 3, 6, 8, 5],
       [1, 6, 2, 5, 8, 9, 7, 3, 4],
       [5, 3, 8, 7, 4, 6, 2, 1, 9]])

In [17]:
np.unique(board, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64))

### Reading sudoku board from image

In [ ]:
# import the necessary packages
from imutils.perspective import four_point_transform
from skimage.segmentation import clear_border
import numpy as np
import imutils
import cv2

def find_puzzle(image, debug=True):
    # convert the image to grayscale and blur it slightly
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (7, 7), 3)
    
    # apply adaptive thresholding and then invert the threshold map
    thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)
    thresh = cv2.bitwise_not(thresh)
    
    # check to see if we are visualizing each step of the image
    # processing pipeline (in this case, thresholding)
    if debug:
        cv2.imshow("Puzzle Thresh", thresh)
        cv2.waitKey(0)
    
    # find contours in the thresholded image and sort them by size in
    # descending order
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
    
    # initialize a contour that corresponds to the puzzle outline
    puzzleCnt = None
    
    # loop over the contours
    for c in cnts:
        # approximate the contour
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.02 * peri, True)
        
        # if our approximated contour has four points, then we can
        # assume we have found the outline of the puzzle
        if len(approx) == 4:
            puzzleCnt = approx
            break
    
    # if the puzzle contour is empty then our script could not find
    # the outline of the Sudoku puzzle so raise an error
    if puzzleCnt is None:
        raise Exception(("Could not find Sudoku puzzle outline. "
            "Try debugging your thresholding and contour steps."))
    
    # check to see if we are visualizing the outline of the detected
    # Sudoku puzzle
    if debug:
        # draw the contour of the puzzle on the image and then display
        # it to our screen for visualization/debugging purposes
        output = image.copy()
        cv2.drawContours(output, [puzzleCnt], -1, (0, 255, 0), 2)
        cv2.imshow("Puzzle Outline", output)
        cv2.waitKey(0)
        
    # apply a four point perspective transform to both the original
    # image and grayscale image to obtain a top-down bird's eye view
    # of the puzzle
    puzzle = four_point_transform(image, puzzleCnt.reshape(4, 2))
    warped = four_point_transform(gray, puzzleCnt.reshape(4, 2))
    
    # check to see if we are visualizing the perspective transform
    if debug:
        # show the output warped image (again, for debugging purposes)
        cv2.imshow("Puzzle Transform", puzzle)
        cv2.waitKey(0)
    
    # return a 2-tuple of puzzle in both RGB and grayscale
    return (puzzle, warped)

In [19]:
sudoku1_path = r"Example\sudoku4.jpg"
sudoku1 = cv2.imread(sudoku1_path)
# debug = True

# puzzle, warped = find_puzzle(sudoku1, debug=debug)

In [20]:
# cv2.imshow("Puzzle", puzzle)
# cv2.waitKey(0)

# cv2.imshow("Warped", warped)
# cv2.waitKey(0)

# cv2.destroyAllWindows()

In [21]:
def extract_digit(cell, debug=False):
    # apply automatic thresholding to the cell and then clear any
    # connected borders that touch the border of the cell
    thresh = cv2.threshold(cell, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
    thresh = clear_border(thresh)
    
    # check to see if we are visualizing the cell thresholding step
    if debug:
        cv2.imshow("Cell Thresh", thresh)
        cv2.waitKey(0)
    
    # find contours in the thresholded cell
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    
    # if no contours were found than this is an empty cell
    if len(cnts) == 0:
        return None
    
    # otherwise, find the largest contour in the cell and create a
    # mask for the contour
    c = max(cnts, key=cv2.contourArea)
    mask = np.zeros(thresh.shape, dtype="uint8")
    cv2.drawContours(mask, [c], -1, 255, -1)
    
    # compute the percentage of masked pixels relative to the total
    # area of the image
    (h, w) = thresh.shape
    percentFilled = cv2.countNonZero(mask) / float(w * h)
    
    # if less than 3% of the mask is filled then we are looking at
    # noise and can safely ignore the contour
    if percentFilled < 0.03:
        return None
    
    # apply the mask to the thresholded cell
    digit = cv2.bitwise_and(thresh, thresh, mask=mask)

    # check to see if we should visualize the masking step
    if debug:
        cv2.imshow("Digit", digit)
        cv2.waitKey(0)
    
    # return the digit to the calling function
    return digit

In [22]:
# load the input image from disk and resize it

print("[INFO] processing image...")
image = cv2.imread(sudoku1_path)
image = imutils.resize(image, width=600)

debug = True

[INFO] processing image...


In [23]:
# find the puzzle in the image and then
(puzzleImage, warped) = find_puzzle(image, debug)

# initialize our 9x9 Sudoku board
board = np.zeros((9, 9), dtype="int")

# a Sudoku puzzle is a 9x9 grid (81 individual cells), so we can
# infer the location of each cell by dividing the warped image
# into a 9x9 grid
stepX = warped.shape[1] // 9
stepY = warped.shape[0] // 9

# initialize a list to store the (x, y)-coordinates of each cell
# location
cellLocs = []

cv2.destroyAllWindows()

In [24]:
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt
from time import time
from torchvision import datasets, transforms
from torch import nn, optim
import torch.nn.functional as F

# n_epochs = 3
# batch_size_train = 64
# batch_size_test = 1000
# learning_rate = 0.01
# momentum = 0.5
# log_interval = 10

# optimizer = optim.SGD(network.parameters(), lr=learning_rate, momentum=momentum)


In [25]:
import os

In [26]:
# if not os.path.isdir('Digitdata'):
#     os.mkdir('Digitdata')
#     for i in range(1, 10):
#         os.mkdir('Digitdata/%d'%i)

### Loading My Model

In [27]:
# hyperparameters
input_size = 784
output_size = 10
hidden_size = 200

class Network(nn.Module):
    
    def __init__(self):
        super(Network, self).__init__()
        self.l1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.l3 = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        x = self.l1(x)
        x = self.relu(x)
        x = self.l3(x)
        return F.log_softmax(x, dim=-1)
    
model = Network()

PATH = 'myModel.pth'
model.load_state_dict(torch.load(PATH))

<All keys matched successfully>

### Code to save digits

In [28]:
# debud=True

# di = 80
# # loop over the grid locations
# for y in range(0, 9):
#     # initialize the current list of cell locations
#     row = []
    
#     for x in range(0, 9):
#         # compute the starting and ending (x, y)-coordinates of the
#         # current cell
#         startX = x * stepX
#         startY = y * stepY
#         endX = (x + 1) * stepX
#         endY = (y + 1) * stepY
        
#         # add the (x, y)-coordinates to our cell locations list
#         row.append((startX, startY, endX, endY))
        
#         # crop the cell from the warped transform image and then
#         # extract the digit from the cell
#         cell = warped[startY:endY, startX:endX]
#         digit = extract_digit(cell, debug=debug)
        
#         # verify that the digit is not empty
#         if digit is not None:
            
#             # resize the cell to 28x28 pixels and then prepare the
#             # cell for classification
#             roi = cv2.resize(digit, (28, 28))
# #             roi = roi.astype("float") / 255.0
#             ans = model(torch.tensor(roi, dtype=torch.float).reshape(1,-1))
# #             print("ans is: ",ans)
# #             print(type(roi))
# #             print(roi)
# #             break
#             num = torch.argmax(ans.data, 1)[0].item()
#             print(num)
#             actual_num = int(input("Num is: "))
#             cv2.imwrite('Digitdata/%d/%d.png' % (actual_num, di), roi)
#             di += 1

# #             roi = img_to_array(roi)
# #             roi = np.expand_dims(roi, axis=0)

# #             # classify the digit and update the Sudoku board with the
# #             # prediction
# #             pred = model.predict(roi).argmax(axis=1)[0]
# #             board[y, x] = num
    
#     # add the row to our cell locations
#     cellLocs.append(row)

In [29]:
cv2.destroyAllWindows()

### Code to build sudoku in python

In [30]:
board = np.zeros((9, 9), dtype=np.int32)
debug = False
# loop over the grid locations
for y in range(0, 9):
    # initialize the current list of cell locations
    row = []
    
    for x in range(0, 9):
        # compute the starting and ending (x, y)-coordinates of the
        # current cell
        startX = x * stepX
        startY = y * stepY
        endX = (x + 1) * stepX
        endY = (y + 1) * stepY
        
        # add the (x, y)-coordinates to our cell locations list
        row.append((startX, startY, endX, endY))
        
        # crop the cell from the warped transform image and then
        # extract the digit from the cell
        cell = warped[startY:endY, startX:endX]
        digit = extract_digit(cell, debug=debug)
        
        # verify that the digit is not empty
        if digit is not None:
            
            # resize the cell to 28x28 pixels and then prepare the
            # cell for classification
            roi = cv2.resize(digit, (28, 28))
#             roi = roi.astype("float") / 255.0
            ans = model(torch.tensor(roi, dtype=torch.float).reshape(1,-1))
#             print("ans is: ",ans)
#             print(type(roi))
#             print(roi)
#             break
            num = torch.argmax(ans.data, 1)[0].item()
#             PIL_roi = Image.fromarray(np.uint8(roi)).convert('RGB')
#             num = getText(PIL_roi)
#             print(num)

#             roi = img_to_array(roi)
#             roi = np.expand_dims(roi, axis=0)

#             # classify the digit and update the Sudoku board with the
#             # prediction
#             pred = model.predict(roi).argmax(axis=1)[0]
            board[y, x] = num
    
    # add the row to our cell locations
    cellLocs.append(row)

In [31]:
old_board = board.copy()

In [32]:
board

array([[0, 0, 0, 0, 9, 0, 5, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [8, 3, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 1, 6, 7, 5, 0],
       [3, 0, 0, 0, 7, 5, 0, 1, 8],
       [0, 5, 0, 0, 0, 0, 0, 9, 0],
       [4, 1, 0, 0, 0, 0, 9, 0, 2],
       [7, 0, 3, 0, 0, 0, 1, 0, 0],
       [0, 2, 0, 6, 5, 0, 0, 0, 4]])

In [33]:
old_board

array([[0, 0, 0, 0, 9, 0, 5, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [8, 3, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 1, 6, 7, 5, 0],
       [3, 0, 0, 0, 7, 5, 0, 1, 8],
       [0, 5, 0, 0, 0, 0, 0, 9, 0],
       [4, 1, 0, 0, 0, 0, 9, 0, 2],
       [7, 0, 3, 0, 0, 0, 1, 0, 0],
       [0, 2, 0, 6, 5, 0, 0, 0, 4]])

In [34]:
is_solved, rules, board = solve(board)

In [35]:
rules

['Put 1 in 3 row, 3 column in bottom middle cell because of 1 in 1, 2 rows and in 2 col',
 'Put 5 in 1 row, 3 column in bottom left cell because of 5 in 3 row and in 2 col',
 'Put 5 in 2 row, 3 column in bottom right cell because of 5 in 3 row and in 1, 2 cols',
 'Put 6 in 2 row, 2 column in top middle cell because of 6 in  and in 3, 1 cols',
 'Put 6 in 2 row, 2 column in bottom left cell because of 6 in 3 row',
 'Put 7 in 3 row, 3 column in center left cell because of 7 in 2, 1 rows and in 1 col',
 'Put 8 in 1 row, 2 column in center left cell because of 8 in 2 row and in 1 col',
 'Put 8 in 3 row, 3 column in bottom left cell because of 8 in  and in 1 col',
 'Put 9 in 3 row, 1 column in bottom left cell because of 9 in 1 row',
 'Put 1 in 3 row, 1 column in center left cell because of 1 in 1, 2 rows and in 2 col',
 'Put 5 in 2 row, 1 column in top left cell because of 5 in 1 row and in 2, 3 cols',
 'Put 6 in 2 row, 3 column in center left cell because of 6 in 1 row and in 2 col',
 'Put

In [36]:
is_solved

True

In [37]:
board

array([[6, 7, 2, 8, 9, 4, 5, 3, 1],
       [5, 4, 9, 1, 6, 3, 8, 2, 7],
       [8, 3, 1, 5, 2, 7, 6, 4, 9],
       [2, 8, 4, 9, 1, 6, 7, 5, 3],
       [3, 9, 6, 4, 7, 5, 2, 1, 8],
       [1, 5, 7, 3, 8, 2, 4, 9, 6],
       [4, 1, 5, 7, 3, 8, 9, 6, 2],
       [7, 6, 3, 2, 4, 9, 1, 8, 5],
       [9, 2, 8, 6, 5, 1, 3, 7, 4]])

In [38]:
added_digits = board - old_board

In [39]:
# rules

In [40]:
def showImage(img):
    cv2.imshow('image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [41]:
stepX = warped.shape[1] // 9
stepY = warped.shape[0] // 9

In [42]:
added_digits

array([[6, 7, 2, 8, 0, 4, 0, 3, 0],
       [5, 4, 9, 1, 6, 3, 8, 0, 7],
       [0, 0, 1, 5, 0, 7, 6, 4, 9],
       [2, 8, 0, 9, 0, 0, 0, 0, 3],
       [0, 9, 6, 4, 0, 0, 2, 0, 0],
       [1, 0, 7, 3, 8, 2, 4, 0, 6],
       [0, 0, 5, 7, 3, 8, 0, 6, 0],
       [0, 6, 0, 2, 4, 9, 0, 8, 5],
       [9, 0, 8, 0, 0, 1, 3, 7, 0]])

In [43]:
old_puzzleImage = puzzleImage.copy()

In [44]:
digit_images = [None] * 10

import glob

glob.glob('Digitdata/*')

j = 1
for j in range(1,10):
    digit_images[j] = cv2.resize(cv2.imread(glob.glob('Digitdata/%d/*' % (j))[0], cv2.IMREAD_GRAYSCALE), (stepX, stepY))


puzzleImage = old_puzzleImage.copy()
for i in range(9):
    for j in range(9):
        if added_digits[i, j] == 0:
            continue
        startX = i * stepX
        startY = j * stepY
        endX = (i + 1) * stepX
        endY = (j + 1) * stepY
        t_im = cv2.bitwise_xor(digit_images[added_digits[i, j]], warped[startX: endX, startY: endY])
        puzzleImage[startX: endX, startY: endY, 0] = t_im
        puzzleImage[startX: endX, startY: endY, 1] = t_im  
#         puzzleImage[startX: endX, startY: endY, 2] = t_im

In [45]:
showImage(puzzleImage)